Question 1

In [10]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2
print(corrected_temperature)

fahrenheit = (9/5) * corrected_temperature + 32
print(fahrenheit)

above_32 = corrected_temperature[corrected_temperature > 32]
print(above_32)

count = np.sum(corrected_temperature > 32)
print(count)

[27 30 33 37 40 29 35 42]
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
[33 37 40 35 42]
5


Question 2

In [11]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print(np.sum(steps))

print(np.mean(steps))

print(np.max(steps))
print(np.min(steps))

print(np.sum(steps, axis=0))

print(np.sum(steps, axis=1))

max_position = np.unravel_index(np.argmax(steps), steps.shape)
print(max_position)

84200
7016.666666666667
9500
4500
[26500 27300 30400]
[18300 24500 14400 27000]
(np.int64(3), np.int64(2))


Question 3

In [12]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]
print(subset)

subset[0] = 999
print(original)
print(subset)

copied_array = original[1:5].copy()
copied_array[0] = 500
print(original)
print(copied_array)

matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

print(matrix[0])
print(matrix[-1])
print(matrix[:, 1])
print(matrix[1:3, 2:4])

flattened = matrix.flatten()
raveled = matrix.ravel()

print(flattened)
print(raveled)

raveled[0] = 100
print(matrix)

flattened[1] = 200
print(matrix)

print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)

[2 3 4 5]
[  1 999   3   4   5   6]
[999   3   4   5]
[  1 999   3   4   5   6]
[500   3   4   5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[ 9 10 11 12]
[ 2  6 10]
[[ 7  8]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
(3, 4)
2
12
int64


Question 4

In [13]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print(X.shape)
print(X.ndim)

print(X.T)

print(X.T @ X)

inverse = np.linalg.inv(X.T @ X)
print(inverse)

beta = np.linalg.inv(X.T @ X) @ X.T @ y
print(beta)

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print(predicted_score)

(4, 3)
2
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
[-0.15921454  0.14083853 10.06302242]
75.27862544778995
